esphome:
  name_add_mac_suffix: true
  friendly_name: dispenser
  project: 
    name: "ZENZ.DISPENSER"
    version: "0.9.0"
  platformio_options:
    board_build.f_cpu: 160000000L

  on_boot:
    priority: -100
    then:
      - output.turn_on: valve_pin

esp8266:
  board: d1_mini

# Enable logging
logger:

# Over-the-Air updates
ota:
  platform: esphome
  password: "your_ota_password_here"

# WiFi Configuration
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Fallback hotspot in case WiFi connection fails
  ap:
    password: "fallback_ap_password"

# Enable captive portal for hotspot
captive_portal:

# Define GPIO Pins as Binary Sensors
binary_sensor:
  - platform: gpio
    id: aerosol_present_real
    internal: true
    pin:
      number: D6
      mode: INPUT_PULLUP
    on_press:
      then:
        - output.turn_off: red_led_pin
    on_release:
      then:
        - output.turn_on: red_led_pin

  - platform: template
    id: aerosol_present
    name: "Aerosol Present"  # 在 UI 上显示的名字
    lambda: |-
      return id(aerosol_present_real).state ? false : true;
    
  - platform: gpio
    id: dispenser_button
    internal: true
    pin: 
      number: D5
      mode: INPUT_PULLUP
    name: "Dispenser Button"
    on_press:
      then:
        - output.turn_off: green_led_pin
        - delay: 1s
        - output.turn_off: valve_pin
    on_release:
      then:
        - output.turn_on: green_led_pin
        - delay: 1s
        - output.turn_on: valve_pin

# Define GPIO Pins as Outputs
output:
  - platform: gpio
    pin: 
      number: D2
    id: red_led_pin

  - platform: gpio
    pin: 
      number: D1 
      inverted: true
    id: green_led_pin

  - platform: gpio
    pin: 
      number: D7
      inverted: true
      mode: OUTPUT
    id: valve_pin

switch:
  - platform: template
    id: aerosol_trigger
    name: "Aerosol Trigger"
    restore_mode: ALWAYS_OFF
    optimistic: true
    turn_on_action:
      then:
        - output.turn_off: green_led_pin
        - output.turn_off: valve_pin
        - delay: 2s
        - output.turn_on: valve_pin
        - switch.turn_off: aerosol_trigger
        - output.turn_on: green_led_pin

# Add Home Assistant API
api: